# Generated by Django 5.1.2 on 2025-02-19 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField()),
                ('environment', models.CharField(max_length=50)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.PositiveBigIntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['processed', 'created_at'], name='core_outbox_process_439d30_idx')],
            },
        ),
    ]
